# Default values for this helm chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1
image:
  registry: "ghcr.io"
  repository: "otherweb/other_back_end"
  tag: "v20230616_1926"
  credentials: 
    username: someone
    password: sillyness

domain: "other-test.com"

environments:
  - name: "ConnectionStrings__Connection"
    value: "Server=tcp:mssql-latest-deploy.sql-data.svc.cluster.local,1433;Initial Catalog=other-uat-database;Persist Security Info=False;User ID=OtherDbUserUat;Password=abc;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
  - name: "BaseUrl"
    value: "https://other-test.com"
  - name: "ASPNETCORE_ENVIRONMENT"
    value: "Production"
  - name: "TZ"
    value: "America/Toronto"

isReleaseDomain: false
