# Default values for mssql-latest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1
namespace: "sql-data"
image:
  repository: mcr.microsoft.com/mssql/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2017-latest"

ACCEPT_EULA:
    value: "y"
MSSQL_PID:
    value: "Express"
MSSQL_AGENT_ENABLED:
    value: "true"
hostname: mssqllatest
sa_password: "SAMPLE_HERE"
# https://docs.google.com/document/d/1gZkXWSD54PcNdc7E7xnLGyAT7X3cCKj7hWTRLP5OF4Y/edit
containers:
  ports:
    containerPort: 1433

podAnnotations: {}

podSecurityContext:
  fsGroup: 10001

service:
  type: ClusterIP
  port: 1433
  typeExternal: LoadBalancer
  portExternal: 33000
  targetPort: 1433

pvc:
  StorageClass: "azure-disk"
  userdbaccessMode: ReadWriteOnce
  userdbsize: 5Gi
  userlogaccessMode: ReadWriteOnce
  userlogsize: 5Gi
  tempdbaccessMode: ReadWriteOnce
  tempsize: 2Gi
  mssqldataaccessMode: ReadWriteOnce
  mssqldbsize: 2Gi
