# Build App
FROM node:14.15.0 as build-env
WORKDIR /app
COPY package.json /app
RUN npm cache verify
RUN npm install
COPY . /app

FROM build-env as testrunner
CMD ["npm", "run", "test"]

FROM build-env as build
RUN npm run dev-deploy

FROM nginx as runtime
COPY --from=build /app/dist/OTHER-Web /usr/share/nginx/html
COPY /nginx.conf  /etc/nginx/conf.d/default.conf
# The command to run our app when the container is run
# Set environments variables to Angular: https://pumpingco.de/blog/environment-variables-angular-docker/
CMD ["/bin/sh", "-c", "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]
