{{- $domainCrt := print "certs/" .Values.domain ".crt" -}}
{{- $domainKey := print "certs/" .Values.domain ".key" -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "default.name" . }}-secrets-tls
  namespace: {{ include "default.name" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get $domainCrt | b64enc }}
  tls.key: {{ .Files.Get $domainKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "default.name" . }}-github-secret
  namespace: {{ include "default.name" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagePullSecret" . }}
