name: Deploy Github Pages

on:
  push:
    branches:
      - main

env:
  GITHUB_REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:

  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npx @marp-team/marp-cli@3.3.1 docs/videos/01_Intro_Backend/Intro_Backend.md -o docs/videos/01_Intro_Backend/index.html
      - run: npx @marp-team/marp-cli@3.3.1 docs/videos/02_Intro_Frontend/Intro_Frontend.md -o docs/videos/02_Intro_Frontend/index.html
      - run: npx @marp-team/marp-cli@3.3.1 docs/videos/03_Demo_Backend/Demo_Backend.md -o docs/videos/03_Demo_Backend/index.html
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: docs/videos
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_REPO_TOKEN }}
